# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash1', models.CharField(max_length=100)),
                ('hash2', models.CharField(max_length=100)),
                ('hash3', models.CharField(max_length=100)),
            ],
        ),
    ]
